mod day1;
pub use day1::NewDay1Puzzle;
mod day2;
pub use day2::NewDay2Puzzle;
mod day3;
pub use day3::NewDay3Puzzle;
mod day4;
pub use day4::NewDay4Puzzle;
mod day5;
pub use day5::NewDay5Puzzle;
mod day6;
pub use day6::NewDay6Puzzle;
mod day7;
pub use day7::NewDay7Puzzle;
