name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # ref: https://github.com/convco/convco/blob/master/.github/workflows/release.yml
  build:
    name: Build
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}
    strategy:
      matrix:
        include:
          - os:
              name: ubuntu
              version: latest
            binary: rust-advent
          - os:
              name: macos
              version: latest
            binary: rust-advent
          - os:
              name: windows
              version: latest
            binary: rust-advent.exe
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Test on ${{ matrix.os.name }}
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Build ${{ matrix.os.name }} binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload ${{ matrix.os.name }} binary
        uses: actions/upload-artifact@v2
        with:
          name: rust-advent-${{ matrix.os.name }}
          path: target/release/${{ matrix.binary }}
